language: node_js
node_js:
  - 10
before_deploy:
  - cd docs
  - npm install
  - npm run build
  - cp src/card.png dist
  - cp src/logo.png dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/dist
  on:
    branch: master
